SET SERVEROUTPUT ON;
DECLARE
    CURSOR CUR_LOANS IS
        SELECT LOANID, INTERESTRATE
        FROM LOANS;
        
    V_LOAN_ID LOANS.LOANID%TYPE;
    V_INTEREST_RATE LOANS.INTERESTRATE%TYPE;
    V_NEW_INTEREST_RATE NUMBER;
    V_NEW_POLICY NUMBER := 2;
    
    FUNCTION CALCULATENEWINTERESTRATE(OLD_RATE NUMBER) RETURN NUMBER IS
    BEGIN
        RETURN OLD_RATE * (1 + (V_NEW_POLICY / 100)); 
    END CALCULATENEWINTERESTRATE;
BEGIN
    OPEN CUR_LOANS;
    
    LOOP
        FETCH CUR_LOANS INTO V_LOAN_ID, V_INTEREST_RATE;
        EXIT WHEN CUR_LOANS%NOTFOUND;
        
        V_NEW_INTEREST_RATE := CALCULATENEWINTERESTRATE(V_INTEREST_RATE);
        
        UPDATE LOANS
        SET INTERESTRATE = V_NEW_INTEREST_RATE
        WHERE LOANID = V_LOAN_ID;
        
        DBMS_OUTPUT.PUT_LINE('Loan ID: ' || V_LOAN_ID || ' interest rate updated to ' || V_NEW_INTEREST_RATE);
    END LOOP;
    
    CLOSE CUR_LOANS;
    
    COMMIT;
END;
/
