SET SERVEROUTPUT ON;

CREATE OR REPLACE FUNCTION HasSufficientBalance(
    P_ACCOUNT_ID IN ACCOUNTS.ACCOUNTID%TYPE,
    P_AMOUNT IN NUMBER
) RETURN BOOLEAN IS
    V_BALANCE ACCOUNTS.BALANCE%TYPE;
BEGIN
    SELECT BALANCE INTO V_BALANCE
    FROM ACCOUNTS
    WHERE ACCOUNTID = P_ACCOUNT_ID;

    RETURN V_BALANCE >= P_AMOUNT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN FALSE;
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error checking balance: ' || SQLERRM);
END HASSUFFICIENTBALANCE;
/


DECLARE
    V_ACCOUNTID ACCOUNTS.ACCOUNTID%TYPE := &Account_id;
    V_AMOUNT NUMBER := &Amount;
    V_HAS BOOLEAN;
BEGIN
    V_HAS  := HasSufficientBalance(V_ACCOUNTID, V_AMOUNT);
    
    IF V_HAS = TRUE THEN 
    	DBMS_OUTPUT.PUT_LINE('Account with id:' || V_ACCOUNTID || ' has sufficient amount');
    ELSE DBMS_OUTPUT.PUT_LINE('Account with id:' || V_ACCOUNTID || ' does not have sufficient amount');
    END IF;
END;
/
