SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION ageCalculator(
	p_DOB DATE
) RETURN NUMBER 
IS
    V_AGE NUMBER;  
BEGIN
    V_AGE := TRUNC((SYSDATE - P_DOB) / 365);
    RETURN V_AGE;
END ageCalculator;
/
  
DECLARE
    CURSOR CURSOR_CUST IS SELECT CUSTOMERID, DOB FROM CUSTOMERS;
    V_CUSTOMERID CUSTOMERS.CUSTOMERID%TYPE;
    V_DOB CUSTOMERS.DOB%TYPE;
    V_AGE NUMBER;
BEGIN
    OPEN CURSOR_CUST;
    LOOP
        FETCH CURSOR_CUST INTO V_CUSTOMERID, V_DOB;
        EXIT WHEN CURSOR_CUST%NOTFOUND;
        
        V_AGE := ageCalculator(V_DOB);
        
        DBMS_OUTPUT.PUT_LINE('Customer id: ' || V_CUSTOMERID || ' , age: ' || V_AGE);
    END LOOP;
    CLOSE CURSOR_CUST;
END;
/
